
def ari8toel(num):
    elements = {
        "Hydrogen": 1,
        "Helium": 2,
        "Lithium": 3,
        "Beryllium": 4,
        "Boron": 5,
        "Carbon": 6,
        "Nitrogen": 7,
        "Oxygen": 8,
        "Fluorine": 9,
        "Neon": 10,
        "Sodium": 11,
        "Magnesium": 12,
        "Aluminium": 13,
        "Silicon": 14,
        "Phosphorus": 15,
        "Sulfur": 16,
        "Chlorine": 17,
        "Argon": 18,
        "Potassium": 19,
        "Calcium": 20,
        "Scandium": 21,
        "Titanium": 22,
        "Vanadium": 23,
        "Chromium": 24,
        "Manganese": 25,
        "Iron": 26,
        "Cobalt": 27,
        "Nickel": 28,
        "Copper": 29,
        "Zinc": 30,
        "Gallium": 31,
        "Germanium": 32,
        "Arsenic": 33,
        "Selenium": 34,
        "Bromine": 35,
        "Krypton": 36,
        "Rubidium": 37,
        "Strontium": 38,
        "Yttrium": 39,
        "Zirconium": 40,
        "Niobium": 41,
        "Molybdenum": 42,
        "Technetium": 43,
        "Ruthenium": 44,
        "Rhodium": 45,
        "Palladium": 46,
        "Silver": 47,
        "Cadmium": 48,
        "Indium": 49,
        "Tin": 50,
        "Antimony": 51,
        "Tellurium": 52,
        "Iodine": 53,
        "Xenon": 54,
        "Caesium": 55,
        "Barium": 56,
        "Lanthanum": 57,
        "Cerium": 58,
        "Praseodymium": 59,
        "Neodymium": 60,
        "Promethium": 61,
        "Samarium": 62,
        "Europium": 63,
        "Gadolinium": 64,
        "Terbium": 65,
        "Dysprosium": 66,
        "Holmium": 67,
        "Erbium": 68,
        "Thulium": 69,
        "Ytterbium": 70,
        "Lutetium": 71,
        "Hafnium": 72,
        "Tantalum": 73,
        "Tungsten": 74,
        "Rhenium": 75,
        "Osmium": 76,
        "Iridium": 77,
        "Platinum": 78,
        "Gold": 79,
        "Mercury": 80,
        "Thallium": 81,
        "Lead": 82,
        "Bismuth": 83,
        "Polonium": 84,
        "Astatine": 85,
        "Radon": 86,
        "Francium": 87,
        "Radium": 88,
        "Actinium": 89,
        "Thorium": 90,
        "Protactinium": 91,
        "Uranium": 92,
        "Neptunium": 93,
        "Plutonium": 94,
        "Americium": 95,
        "Curium": 96,
        "Berkelium": 97,
        "Californium": 98,
        "Einsteinium": 99,
        "Fermium": 100,
        "Mendelevium": 101,
        "Nobelium": 102,
        "Lawrencium": 103,
        "Rutherfordium": 104,
        "Dubnium": 105,
        "Seaborgium": 106,
        "Bohrium": 107,
        "Hassium": 108,
        "Meitnerium": 109,
        "Darmstadtium": 110,
        "Roentgenium": 111,
        "Copernicium": 112,
        "Nihonium": 113,
        "Flerovium": 114,
        "Moscovium": 115,
        "Livermorium": 116,
        "Tennessine": 117,
        "Oganesson": 118
    }
    prama = [prama for prama, val in elements.items() if val == num]
    return prama[0]

data = [{"Στοιχειο":"Λίθιο ","Ατομ.αρ.":"3","":"","πληροφοριες1":"Το λίθιο είναι ένα αλκαλικό μέταλλο με χημικό σύμβολο Li και ατομικό αριθμό 3. Είναι το ελαφρύτερο μέταλλο και αντιδρά έντονα με το νερό.","πληροφοριες2":"Το λίθιο χρησιμοποιείται σε μπαταρίες ιόντων λιθίου, που τροφοδοτούν κινητά τηλέφωνα, φορητούς υπολογιστές και ηλεκτρικά οχήματα.","πληροφοριες3":"Ανακαλύφθηκε το 1817 από τον Σουηδό χημικό Γιόχαν Αρφβέντσον, ενώ μερικές από τις μεγαλύτερες φυσικές αποθέσεις του βρίσκονται στη Νότια Αμερική."},{"Στοιχειο":"Οξυγόνο ","Ατομ.αρ.":"8","":"","πληροφοριες1":"Είναι το πιο άφθονο στοιχείο στη Γη.","πληροφοριες2":"","πληροφοριες3":""},{"Στοιχειο":"Νάτριο ","Ατομ.αρ.":"11","":"","πληροφοριες1":"Ρυθμίζει τη μετακίνηση των υγρών στα κύτταρα.","πληροφοριες2":"","πληροφοριες3":""},{"Στοιχειο":"Χλώριο ","Ατομ.αρ.":"17","":"","πληροφοριες1":"Ρυθμίζει την ισορροπία του νερού στο σώμα.","πληροφοριες2":"","πληροφοριες3":""},{"Στοιχειο":"Ασβέστιο","Ατομ.αρ.":"","":"","πληροφοριες1":"","πληροφοριες2":"","πληροφοριες3":""},{"Στοιχειο":"Μαγνήσιο","Ατομ.αρ.":"","":"","πληροφοριες1":"","πληροφοριες2":"","πληροφοριες3":""},{"Στοιχειο":"Φώσφορος","Ατομ.αρ.":"15","":"","πληροφοριες1":"Διατηρεί τα οστα και τα δόντια δυνατά","πληροφοριες2":"","πληροφοριες3":""},{"Στοιχειο":"Κάλιο","Ατομ.αρ.":"19","":"","πληροφοριες1":"","πληροφοριες2":"","πληροφοριες3":""},{"Στοιχειο":"Σίδηρος ","Ατομ.αρ.":"26","":"","πληροφοριες1":"Είναι απαραίτητο μέταλλο για τον οργανσμό.","πληροφοριες2":"","πληροφοριες3":""}]

#print(data)
pargas = """    if(tsex == \"""" + ari8toel(int(data[0][("Ατομ.αρ.")])) +"""\") {
        if(typos==0){
            return(`            <li>""" + (str(data[0][("πληροφοριες1")])) +"""</li>
                <li>""" + (str(data[0][("πληροφοριες2")])) + """</li>
                <li>""" + (str(data[0][("πληροφοριες3")])) + """</li>`)
        }
        else{
            return(\"""" + (str(data[0][("Στοιχειο")])) +"""\")
        }"""
print(pargas)